### ISSUE TITLE
Cannot Be Cloned

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [lilydjwg/socat#1]
This repository cannot be cloned as described below:

``fatal: Authentication failed for 'https://github.com/lilydjwd/socat.git/'``

**Comment by lilydjwg** [comment]
You misspelled my github username.

**Comment by De-Been-Tech-Solutions** [comment]
Ok well, your repository still requires a username and password to clone.

``fatal: authentication error: requires personal token``

**Comment by De-Been-Tech-Solutions** [comment]
Or similar.

**Comment by lilydjwg** [comment]
No, I just tested it. Make sure you've got the right URL. (Or post what you see as a screenshot to diagnose.)

**Comment by De-Been-Tech-Solutions** [comment]
Ok, well, I know what I saw, and your repository requires the users password and username.

**Comment by lilydjwg** [comment]
> your repository requires the users password and username.

Nope. This repository is as public as any other public repository on GitHub. Either you misspelt, or you misconfigured.
